### ISSUE TITLE
Civic Square neighbourhood (85773603) is not correct

### ISSUE THREAD

**Issue by orangejulius** [whosonfirst-data/whosonfirst-data-admin-au#1]
We've recieved reports from geocode.earth users that the neighbourhood geometry, which is sourced from quattroshapes, is definitely not correct. We're filtering it out for now, but wanted to pass it along in case you wanted to deprecate it or mark it funky.

**Comment by stepps00** [comment]
Thanks @orangejulius!

I'm closing this in preference of https://github.com/whosonfirst-data/whosonfirst-data/issues/1620; let's chat about the updates through that issue.
